### ISSUE TITLE
points

### ISSUE THREAD

**Issue by kikiegoguma** [alexprengere/medoids#1]
how to change points with 2D array?
i try to change points : 

points = np.array([[1,1], [2,2],[10,10], [12, 12], [13, 13]])

> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by alexprengere** [comment]
The reason this does not work is because of the test `if not points` at the very beginning of the process.
Apparently numpy arrays does not implement `__bool__` in the expected way here, so I pushed 106d9c6eeddb77861c8f663aef6e1259c800d67c that actually tests `if len(points) == 0` instead. Could you check that it works for you?

**Comment by Jarino** [comment]
I realize this is two years old issue, but if anyone stumbles on this, the problem is actually on line 59:

```
medoids = [Medoid(kernel=p) for p in random.sample(points, k)]
```

and on line 80:

```
if new_kernel != m.kernel:
```

In the first case, `random.sample` won't work for numpy.ndarray and the second case is actually the ValueError OP is pointing at (note that I'm using python 3.6).

I [forked the repository](https://github.com/Jarino/medoids) and pushed version of `medoids.py` which works with numpy arrays (not sure whether this works with pypy).

**Comment by alexprengere** [comment]
Thanks for reviewing this, could you open a PR so I can review/merge the changes?

**Comment by Jarino** [comment]
PR here: https://github.com/alexprengere/medoids/pull/2
